### ISSUE TITLE
When do tween Plans compound vs. clobber

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#10]
From a comment I wrote in TweenPerformerWeb:

> I'm being super naïve here because I'm not entirely sure what the difference should be between `to` and `by`.  `from` and `to` are absolute terms, but absolute relative to which coordinate space?  Are they relative to wherever the element happens to be, to the viewport, or to the document?  Does the answer differ for moves versus fade, scales, or rotations?  If it's absolute to the document, and we receive a `fadeIn`, how do we handle cases where an ancestor has a translucent opacity?

Also relevant, plans may not arrive at the same time, e.g. if a `moveTo()` is executing and a `moveBy()` arrives in the middle, the `by` should probably compound onto the `to`.

**Comment by appsforartists** [comment]
Related: #23

**Comment by jverkoey** [comment]
I've added some considerations to https://material-motion.github.io/material-motion/starmap/specifications/plans/Tween.
