### ISSUE TITLE
Write a script that will run build commands for every folder in `packages`

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#109]
After #108 lands, we should complete the work by moving the remaining devDependencies (`tsc` and `tslint`) into the package root.  Currently, that's blocked on `$( yarn bin )/tsc` resolving to the local package.  Therefore, we should write a script that does something like this:

```javascript
// build.js
const tsconfigs = globSync('./packages/*/tsconfig.json');
tsconfigs.forEach(
  tsconfig => {
    exec(`$( yarn bin )/tslint -c ../../tslint.json --project ${ tsconfig }`);
    exec(`$( yarn bin )/tsc --project ${ tsconfig }`);
  }
);
```
 and call it with `yarn run build` from the root `package.json`.  This will enable us to move all the `devDependencies` into the project root.

**Comment by tofuness** [comment]
Diff http://codereview.cc/D2382

**Comment by appsforartists** [comment]
When you run `review`, it should link the diff here for you; and when you run `land`, it should close it.
