### ISSUE TITLE
Implement Scheduler.isIdle

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#11]
Can probably be implemented with an RxJS subject and a distinct operator.

**Comment by appsforartists** [comment]
@jverkoey why is this not blocking next release? :eyebrow: 😕

**Comment by jverkoey** [comment]
Everything in a milestone is blocking the next release (the milestone). Probably going to remove that tag.

**Comment by appsforartists** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1300
