### ISSUE TITLE
test.js

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#112]
- each package.json should include the line `"test": "node ../../test.js ${ packageName }"`
- test.js should run the tests for the whole repo:
  - http://karma-runner.github.io/1.0/dev/public-api.html
- as a follow-up, we can teach test.js to only run tests for the package name it receives as an argument

So,

```
streams$ yarn run test
# node ../../test.js streams
# which runs karma.start()
```

**Comment by tofuness** [comment]
Here are some of my thoughts on this 😃 

* If we add a `yarn run test` script to every package, then we should also support other package-level scripts like `yarn run lint` or `yarn run build` (`node ../../lint.js` and `node ../../build.js`). The great thing about this, in my opinion, is that it feels very _node-like_ to develop packages this way 👍 .

* I've looked a bit at how Babel solved this ([Babel CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)) and it seems like they currently run everything (tests, builds, linting) from the root directory. This allows the package-level `package.json` to contain less metadata. For a Babel package maintainer/contributor, this probably means that they can focus more on the package and spend less time figuring out how all `package.json` scripts works.

* I think if the number of packages for this project is going to be low, we should continue with your initial proposal!

**Comment by tofuness** [comment]
Closing. Added with https://github.com/material-motion/material-motion-js/commit/d7f348f5995b497320cba9e172e06933715307d5 .
