### ISSUE TITLE
Add codecov

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#123]
I used nyc in indefinite-observable, but we're using karma in MM to make sure the DOM code works in browsers.  I think nyc is designed to wrap mocha (independent of karma).

https://github.com/karma-runner/karma-coverage looks like it might work.

**Comment by appsforartists** [comment]
🎊 My diff is ready for review at http://codereview.cc/D2537

**Comment by appsforartists** [comment]
💻 I'm working on a diff at http://codereview.cc/D2537

**Comment by appsforartists** [comment]
I've experimented with getting codecov to work.  Unfortunately, [`karma-coverage`](https://github.com/karma-runner/karma-coverage) doesn't wait for `webpack` to finish, and the `webpack` solution ([istanbul-instrumenter-loader](https://github.com/deepsweet/istanbul-instrumenter-loader)) doesn't play nicely either:

```
ERROR in ./packages/testing-utils/src/useMockedRAF.ts
Module build failed: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (17:0)
```

Seems like the simplest solution would be to remove `webpack` from our test infrastructure altogether: we could build the source and tests before starting karma, and use `karma-coverage` for instrumentation.

**Comment by appsforartists** [comment]
Starting to replace Webpack with requirejs:

http://codereview.cc/D2557
http://codereview.cc/D2558

**Comment by jverkoey** [comment]
@tofuness feel free to reassign if you'd like to tackle this again :)

**Comment by appsforartists** [comment]
I just realized: when `<script type=module>` [lands](https://www.chromestatus.com/feature/5365692190687232), we can get rid of Webpack entirely and have a simple `yarn run build; yarn run test` workflow (like we do in indefinite-observable) while still testing in real browsers!
