### ISSUE TITLE
high priority: choose a focus project for the web

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-experiments-js#13]
This is a high priority task. Let's use this thread to discuss ideas.

Some places in which we can make an impact:
- Documentation for material motion. Explaining the ideas and providing interactive examples to be played with.

**Comment by appsforartists** [comment]
Should we close this?

**Comment by jverkoey** [comment]
Yeah, but the theme is still relevant. Theme being to consider practical applications of the tech on the web.
