### ISSUE TITLE
Transitions and URLs

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#14]
The Material Motion architecture is designed for transitions [between known states](https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/transitions.html).  On the Web, links make it easy to go between arbitrary states, and the resulting combinatoric explosion might make it impractical to define Directors between every permutation.

A common refrain in the {React, Ember} communities is ["if your UI is nested, your routes should be."](https://twitter.com/wycats/status/296647717311102979).  Perhaps we can use this nesting to find the appropriate Director to manage a transition between different branches of the route tree.  If there's no director to go from one leaf to another, maybe there's one to transition out of a particular parent view and into another one.

**Comment by appsforartists** [comment]
One possibility (not a suggestion, just a braindump from old notes):

Directors normally transition between state A and state B.  You could also have a transition that transitions between state A and state not-A.  Use that as the fallback if a more specific one isn't available.  You could also have a default director that transitions from not-B to B.  Together, you have an impromptu transition between A and B.

This can be problematic (for instance, if both A.out and B.in are fades, you'll see through both views during the transition).  Perhaps that's OK, because the author can see it and know to build something more specific.

**Comment by appsforartists** [comment]
More old notes, this time from when I asked @jverkoey about how you avoid a combinatoric explosion when each transition needs an A and a B side:

> - Directors presume that certain assets are in a from or a to view, but don’t care which particular view that is.  For instance, Listen Now and Strfkr might each show an album card.  Tapping that album card would lead to the Album Details view.  An `AlbumCardToDetailsDirector` would only care that an album card is on the from view, not that the from view is Listen Now.  The same director could be used for both transitions.
> - Intentions are highly composable.  You can define an intention that describes a certain group of intentions, and reuse that across similar-but-different directors without repeating code.

**Comment by appsforartists** [comment]
Saving this article for later:

https://medium.com/@mattburgess/framework-routers-and-linking-98398af89022#.jfoogrg41

**Comment by jverkoey** [comment]
Closing this until we start tackling transitions on the web.
