### ISSUE TITLE
z-indexing, stacking contexts, and replicas

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#15]
[Stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) and [z-indexing](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index) are expected to be some of the harder complications of bringing Directors to the Web.  
## Expected Ramifications
- [Replicas](https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/duplication.html) may not be feasible, as correctly interleaving replica elements to match the elements they clone will be quite challenging. 
- Directors will likely need to pick one view to be on top and another to be on bottom.  Interleaving views between the two is likely infeasible.

**Comment by appsforartists** [comment]
This also makes scrims tricky, since they're presumably coupled to whatever view drew them.

**Comment by appsforartists** [comment]
One potential solution: make replication an opt-in feature.  If a plan includes a z-index, presume it's OK to temporarily hide the target and use a replica at the desired z-index for the duration of the transition.  Of course, any items that weren't explicitly replicated would be stuck in the background due to stacking contexts.

**Comment by jverkoey** [comment]
Closing this until we know we intend to pursue replication on the web.
