### ISSUE TITLE
Replicas and Style Inheritance

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#16]
Replicas on the Web are very low on the priority list because of stacking contexts (#15).  Even if we solved that, style inheritance would still make replicas hard to do correctly.

If you recursively ran `getComputedStyle` on a source element, could you use that information to faithfully create a replica?  How expensive would this be (e.g. how many elements could you replicate before jank becomes apparent)?

**Comment by appsforartists** [comment]
We could have a dev mode that checked if a replica had different bounds than its target and logged a warning.

**Comment by jverkoey** [comment]
Closing this until we know we plan to pursue replication on the web.
