### ISSUE TITLE
Scroll position

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#18]
What happens if somebody tries to scroll during a transition?  Likely want to let the author specify a behavior (though choose a good default).

How much of scroll position between states should we manage?  How much of it should be left to the author's routing framework?

**Comment by appsforartists** [comment]
https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration?hl=en

**Comment by jverkoey** [comment]
Closing this until it becomes a real issue.
