### ISSUE TITLE
slidingWindow operator

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#199]

**Comment by jverkoey** [comment]
Is this critical for an MVP?

**Comment by appsforartists** [comment]
It's needed for `velocity`.  I can certainly see an argument that `velocity()` isn't critical for an MVP though.

It's effectively [`pairwise()`](https://github.com/staltz/xstream/blob/master/EXTRA_DOCS.md#pairwise), but with a variable length to the resulting array.  I think RxJS calls it [`bufferCount()`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-bufferCount).  I need to be able to compare the locations of the last `n` points to compute velocity.

**Comment by jverkoey** [comment]
Ah! Ok. I confused this with the slidingThreshold operator you were building. Carry on!

**Comment by appsforartists** [comment]
Definitely open to names.  `groupwise` or `inGroupsOf` could be other options…

**Comment by jverkoey** [comment]
Defer to community names if there's a thing for sure - I don't have much of an opinion here because we likely won't need this operator on Swift.

**Comment by appsforartists** [comment]
I generally agree.  `bufferCount` is a modification of Rx's `buffer` operator (which I don't think we'll need), so I'm not sure that name is as clear as it could be.

**Comment by appsforartists** [comment]
🎊 My diff is ready for review at http://codereview.cc/D3088
