### ISSUE TITLE
Automatic transitions

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#20]
If we know what kinds of transitionables are in the from and to views, can we pick the right director to go between them?

**Comment by jverkoey** [comment]
Note that a concrete implementation of this might still resemble a "Director" of sorts, but that Director has a lot of intuition about how best to hook things together.

Another way of structuring this is to allow Directors to lean on some form of "oracle" entity that is able to dispense plans, given a set of desired goals. This may be more scalable than making a single Director type that does all the things (and allows for composition, configuration, all that 🎷 ).

**Comment by jverkoey** [comment]
Example code:

```
TransitionDirector: Director {
  function setUp(transaction) {
    plans = oracle.describePlansFor(leftState, rightState)
    // Maybe change the plans if we don't like them here.
    transaction.add(plans)
  }
}
```

**Comment by jverkoey** [comment]
I like the term oracle because it could legitimately be a system that learns over time and reacts to different contexts in different ways.

**Comment by jverkoey** [comment]
To capture the conversation and start spec'ing this idea out further: https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/a_consultation_interface.html

**Comment by jverkoey** [comment]
Moved to https://github.com/material-motion/material-motion-starmap/issues/52.
