### ISSUE TITLE
Dynamic spring stiffness

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#21]
Would be cool to calculate the longest distance in a transition and use that to dynamically set spring stiffness such that the whole thing completes in a reasonable amount of time.

**Comment by jverkoey** [comment]
This is def a cool piece of math we should house in the starmap.

[One of my favorite papers](http://www.people.fas.harvard.edu/~djmorin/waves/oscillations.pdf). Is on the topic of oscillations.

**Comment by jverkoey** [comment]
Moved to https://github.com/material-motion/starmap/issues/116
