### ISSUE TITLE
Coordinate spaces for moves

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#23]
When executing a move, it can be relative to the viewport or to the document.  The difference is apparent when scrolling: document-relative moves will scroll with the document; whereas, viewport-relative moves will not.

There are situations where you'd want either/both.  For instance, the photos demo should probably be viewport-relative when a photo is expanding, but document-relative when it's collapsing.  

Which do we want to do by default?  What syntax should we use for specifying this?  Perhaps 
- `move().to({ x: 200, y: 200 }).in(DOCUMENT)`, and 
- `move().to({ x: 200, y: 200 }).in(VIEWPORT)`?

**Comment by jverkoey** [comment]
@pingpongboss did some good research here.

**Comment by jverkoey** [comment]
Moved to https://github.com/material-motion/material-motion-starmap/issues/51.
