### ISSUE TITLE
Project status for humans?

### ISSUE THREAD

**Issue by estaub** [material-motion/material-motion-experiments-js#244]
Is the overall status of this project available somewhere?  

Others' needs will differ, but I'm tracking to see if/when it makes sense to evaluate.  

If the core API is firm, it may be of value to provide a status on each component; tell folks what's pretty solid and what's not.  On the other hand, if global changes to the API are likely, say so.

The "Releases" UI, which often gives clues, is spammed: https://github.com/material-motion/material-motion-js/releases.  You probably will want to shut off the spam before humans need it.

(not stalking ;-))

**Comment by appsforartists** [comment]
Hi Ed,

I would say the current API is usable, but not production ready.

I've built many gestural prototypes internally with the code shared here, but I haven't run it through Closure Compiler to verify that it minifies reasonably.  We also need much more thorough documentation and code samples.  While I don't have any immediate plans to change the API, I will do so if it improves the minification story.  For instance, I could see us moving to [pipeable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md), as RxJS has.

The Releases tab is an unfortunate side effect of our code review + continuous integration system (Phabricator + CircleCI).  Until there is better integration between them, I don't think the Releases tab will get less noisy.  Hopefully a changelog + a release history on npm will suffice.

As you may have gathered from my commit history, I've been preoccupied helping out another team recently.  I hope to return my focus here in a few months' time.

Thanks for your interest!  Feel free to explore in the interim.  It is a really powerful system for building interactive interfaces, but it needs better explanation before I'll promote it too widely.
