### ISSUE TITLE
Nestable timelines, e.g. mapRange

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#25]
Would be cool to be able to define a sequence of plans on one timeline, and mount that in a greater timeline.

For instance:

``` javascript
innerTimeline: {
  0: planA,
  .5: planB,
  1: planC,
};

mapRange(
  innerTimeline,
  .5,
  .75
) === {
  .5: planA,
  .625: planB,
  .75: planC,
}
```

**Comment by jverkoey** [comment]
This will be supported by timeline spec. Let's discuss in starmap.
