### ISSUE TITLE
Replicas and interactivity

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#26]
Even if #15 and #16 were solved, you'd have to make sure the replica was seamlessly interactive (e.g. worked just like the original).  Even if #22 says elements shouldn't be interactive mid-transition, there's the time at the end where the transition _feels_ complete, even if the spring is still technically settling.

**Comment by jverkoey** [comment]
Closing this until we know that replication is a feature we intend to build on the web.
