### ISSUE TITLE
Make TweenPerformerWeb more robust

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#4]
TweenPerformerWeb doesn't know how to handle multiple simultaneous plans, because most tweens overload `transform`, so they get overwritten.
- Absolute plans (`from` or `to`) should probably clobber previous ones.  Relative ones (`by`) should probably compound on top of absolute plans.
- Need to be able to introspect a current transform and dissect it into its constituent parts, maybe with https://github.com/web-animations/web-animations-js/blob/master/src/transform-handler.js ?
- May need to remember currently-executing Plans to know which order to apply transformations in.
- WebAnimation Timelines.  Can we even?

Best path forward is probably to make `TweenPerformerReact` (https://github.com/material-motion/material-motion-experiments-js/issues/5) and apply learnings here.

**Comment by jverkoey** [comment]
Closing this with the hopes that we can identify some actionable tasks to file here.

I've moved the description to the milestone itself: https://github.com/material-motion/material-motion-experiments-js/milestone/1
