### ISSUE TITLE
Document deviations from Google Style

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#42]
The next version of the Google Style Guide is way more prescriptive than the current one.  I expect most of it we'll want to use wholesale (and we should [update eslint-config-google accordingly](https://github.com/google/eslint-config-google/issues/18)).  However, it may be worth considering if there are places we may want to deviate.  

For instance, Google Style is to end protected member names with underscores.  Externally, you'd typically begin protected names with underscores.  Since they're protected, maybe we should just follow Google Style.  However, it's also worth considering if this would make our project feel more alien/less endemic to the OSS community.

Note: `.eslintrc` is [already thoroughly commented](https://github.com/material-motion/material-motion-experiments-js/blob/develop/.eslintrc).  This may be enough, or it may be worth documenting it more explicitly (e.g. in a Markdown file).

**Comment by appsforartists** [comment]
On the same note, we should document our project's style (e.g. if we decide to column-align or quote keys in dictionaries).

**Comment by appsforartists** [comment]
May be worth using kebab-case file names (which is Google Style) to make it clear that files are modules and not necc. just a default class/function (esp. they grow over time).

**Comment by jverkoey** [comment]
I believe this is being documented by our typescript linter file now.
