### ISSUE TITLE
Add Challenges to README

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#45]
### Challenges

Quite simply, the Web wasn't designed for layered transitions between states or
for gestural interactivity.  Architectural limitations to be aware of are listed
here.  Actionable experiments are listed in 
[Issues](https://github.com/material-motion/material-motion-experiments-js/issues/).

but with links to the relevant issues for important platform-level concerns.

**Comment by jverkoey** [comment]
Closing this. Let's use starmap to discuss high-level challenges on a given platform.
