### ISSUE TITLE
Use bundle splitting to remove MaterialMotion from examples.js

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#49]
This will also help with #6.

**Comment by jverkoey** [comment]
Is there documentation on what bundle splitting is or how to do it?

**Comment by appsforartists** [comment]
http://webpack.github.io/docs/code-splitting.html

**Comment by appsforartists** [comment]
The more I think about this, the more I'm not sure I care.  Until the loading part of the module spec (and HTTP2) are settled and implemented across browsers, authors are going to be bundling our library into their own packages anyway, so the utility in separating this probably doesn't justify the effort.

Closing until I change my mind.
