### ISSUE TITLE
TweenPerformerReact

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#5]
Build a manually-driven Performer (TweenPerformerReact):
- Use RxJS to build a time stream that emits timestamps from `requestAnimationFrame` and subscribe to it with `TweenPerformerReact`'s `next` function.
  - `Scheduler` should probably remove the subscription when `TweenPerformerWeb` signals that it's at-rest.
- Use [`bezier-easing`](https://www.npmjs.com/package/bezier-easing) for interpolation.
- Support fulfilling multiple plans concurrently.
- Interruptability - what and how?

Eventually, I should be able to go to https://material-motion.appspot.com/expressions/, click the Animate button, and have both semicircles move in unison, even though they are powered by separate Performer systems.

**Comment by jverkoey** [comment]
Similarly here, I've moved this description to the milestone. Let's file issues for specific things to be built/researched/explored.

https://github.com/material-motion/material-motion-experiments-js/milestone/2
