### ISSUE TITLE
Ensure TimeStream treats each observer equally

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#50]
Manual performers should match the execution of delegated performers.  Thus, if `element.animate` starts moving on the same frame it's called, we should too.  If it doesn't, we shouldn't.

There are a lot of little details to get right here:
- Does it do the right thing for the first observer?
- Does it for the second?
- How do you ensure that each observer gets exactly one `next` on every frame?

Trying to make this perfect is a distraction from the greater goal of prototyping a manual performer, so I'm punting on this for now.

One solution might be to make each manual performer responsible for tracking how long it's been since its own `next` was called and doing the right thing.  Then, it's not the concern of the system, and each performer can decide whether to start on frame 0 or frame 1.

**Comment by jverkoey** [comment]
Closing this due to new spec changes that likely resolve this.
