### ISSUE TITLE
Implement pointersStream

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#64]
On every `pointer{down,move,up}`, dispatch an array of all the current pointers.

**Comment by appsforartists** [comment]
A naïve version of this would be

``` javascript
observableFrom(
  [
    'pointerenter',
    'pointerdown',
    'pointermove',
    'pointerup',
    'pointercancel',
    'pointerout',
    'pointerleave',
    'gotpointercapture',
    'lostpointercapture',
  ].map(
    type => observableFromEvent(target, type)
  )
)::mergeAll()::groupBy(
  event => event.pointerId
);
```

but that's not super helpful.  We don't care about most of the non-core pointer events, but would want to handle down, move, and up independently.

**Comment by appsforartists** [comment]
For the streams I need to implement, I don't think I need to even bother grouping by pointerId.  If we can batch them into frames, we can map each frame into {position,rotation,scale} in the appropriate streams.

**Comment by appsforartists** [comment]
Prototyping this in [this pen](http://codepen.io/appsforartists/pen/yaJLZp?editors=0011)

**Comment by appsforartists** [comment]
Should `takeUntil(event.buttons & 1 == 0)` to ensure that we only pay attention to events that include the primary button being depressed.  That means is a particular pointer has the primary button down, then releases it without releasing all the buttons, then depresses it again, `pointerStream` will ignore it.  Since this seems edge-casey, that should be fine for a first version.

We can always write a custom observable after the basics of direct manipulation are implemented and tested to handle this edge case.

**Comment by appsforartists** [comment]
[Working pen](http://codepen.io/appsforartists/pen/ALLNgO)

**Comment by appsforartists** [comment]
💻 I'm working on a diff at http://codereview.cc/D1692

**Comment by jverkoey** [comment]
Deprecated by latest spec.
