### ISSUE TITLE
Implement DirectManipulationPerformer

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#69]

**Comment by appsforartists** [comment]
Not dragging if the user is tapping is a concern on other platforms - do we need to specifically design for it here?  What's the best way to do so?

**Comment by appsforartists** [comment]
Perhaps include a threshold on the Draggable plan that's the minimum distance the user must move in order for that plan to be the winning one (e.g. 8dp).  This would differentiate drags and taps, and also X drags vs Y drags (e.g. for a nested carousel).

What would happen if the user hits the X threshold first, but the overall gesture is clearly trying to move in the Y direction?  Should it be correctable?

**Comment by jverkoey** [comment]
Obsolete.
