### ISSUE TITLE
Distribution strategy

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#7]
- Do we include JS bundles in the GitHub repo?
  - @jverkoey is mildly skeptical, but many other projects do it
  - @traviskaufman is probably also interested
- Should probably have 3 targets:
  - Raw source, complete with Flow annotations and experimental Babel syntaxes
  - [Closure](https://github.com/google/closure-compiler/)-friendly build that converts Flow annotations and experimental syntax into JSDoc and ES2015.  Let Closure handle any transformations beyond that (including, perhaps, parsing `import`/`export`).
  - Single-file bundle, for browsers
- Release process should generate the above targets, run the appropriate tests on each, and push to the relevant places
- Do we host the browser-friendly bundle on a CDN?

Loosely-related: https://github.com/material-motion/material-motion-experiments-js/issues/3

**Comment by jverkoey** [comment]
Skeptical only insofar as the amount it affects day-to-day engineering. If every diff needs to regenerate a large file then this will introduce a decent amount of technical overhead to code review, rollbacks, and diff workflows.

If the assets are only generated on release then this skepticism is lessened.

**Comment by jverkoey** [comment]
Turned this in to a milestone: https://github.com/material-motion/material-motion-experiments-js/milestone/6
