### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#73]
Travis CI

**Comment by appsforartists** [comment]
@seanoshea We could add this to the root `package.json`:

```
  "scripts": {
    "test": "$(yarn bin)/lerna test"
  },
```

which would make `yarn run test` work anywhere in the repo.  (It would test all the packages if you're in the root, or just the package you're in if you have `cd`ed to a particular one.)  It also means we're only depending on one global being installed on the system (`yarn`).

TBH, I don't have a whole lot of experience with unit testing in JS.  I used Karma because it's a Google product, so it should be easy to get internal support for.  Since Karma spins up a bunch of browsers, I'm not sure what happens if you have a dozen instances of Karma running in parallel (one for each package).

**Comment by seanoshea** [comment]
@appsforartists - looking good. I believe there's a headless karma unit test runner that we could use which wouldn't necessitate having to run a bunch of browsers on CI. Have done this in the past with previous projects and it has worked nicely.

**Comment by appsforartists** [comment]
https://github.com/justinribeiro/dockerfiles/blob/master/chrome-headless/Dockerfile

headless mode is coming to chrome.  we could probably add a last member to that array that [points to `localhost:9876`](http://karma-runner.github.io/1.0/config/browsers.html) and expose the right ports and then use [this travis.yml](https://github.com/justinribeiro/lighthouse-mocha-example#try-it-out) and a tweaked karma config to talk to that version of chrome, but I'd rather just wait until the binaries are released and we can use the same chrome karma driver as everybody else.

**Comment by tofuness** [comment]
I loosely followed this guide and managed to get `packages/runtime` tests on Chrome to pass:
http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/

`.travis.yml`: https://github.com/tofuness/material-motion-js/blob/develop/.travis.yml
I think the most relevant part is the `before_install:` section.
(https://travis-ci.org/tofuness/material-motion-js)

I hope it helps 😃

**Comment by appsforartists** [comment]
Very helpful.  Thank you!

Let's avoid caching anything for the time being.  I'd rather know our builds are building correctly than save a few seconds of CPU time on a VM.  If this becomes a problem, we can always change it back.

I'd also love if we could replace the `install` block there with `yarn run bootstrap` from #107, which means we can get rid of the `before_script` block as well.

Finally, it [looks like `lerna` eats console output](https://github.com/lerna/lerna/issues/394), which means we either need to find a `karma-reporter` it won't eat, or run the tests outside of lerna.  Looks like lerna itself [runs tests in the root package.json](https://github.com/lerna/lerna/blob/master/package.json#L11).

Based on all that, I'm thinking we ought to move `karma.conf.js` from `packages/runtime` into the root, and move [this line](https://github.com/material-motion/material-motion-js/blob/develop/packages/runtime/package.json#L10) into the [root package.json](http://codereview.cc/D2200).  It'll run all tests across all packages with one command from the root repo - no need to worry about parallel karma runs or lerna eating test output.  If either of you wants to tackle that, let me know.  I'm happy to do it, but I know you've both put plenty of time into this, and it feels good to [show up in the contributors page](https://github.com/material-motion/material-motion-js/graphs/contributors).  😃

**Comment by appsforartists** [comment]
Here's a working version of [.travis.yml for indefinite-observable](https://github.com/material-motion/indefinite-observable-js/commit/1d0664b2eb6af326e0ad386e4e94170d34fcb538).  It's failing right now because Webpack and the TypeScript build are disagreeing with each other.

I'm tempted to write a ci script that builds the tests in dist and runs those instead, so we can kill Webpack completely (except for _maybe_ quick local testing?)

**Comment by appsforartists** [comment]
I've got [CI working on indefinite-observable](https://github.com/material-motion/indefinite-observable-js/commits/ci), by removing karma and webpack from the equation.  (If we ever wanted to test in browsers, we'd need to add those back.)

https://travis-ci.org/material-motion/indefinite-observable-js

You can see [the setup in package.json](https://github.com/material-motion/indefinite-observable-js/blob/5829faf47e5f5160924e4a96c281ed0311595e6f/package.json#L8).  

- First, it runs the linter.
- Then, it builds the whole project.  This is good to check for any build errors.
- Then, it builds the tests in a separate pass, because we don't care about types for the tests.
- And finally, it runs the tests.

Seems like a reasonable strategy for indefinite-observable.  I like that it checks all-the-things.  Not sure if we should have something lighter-weight for quick runs locally.  Takes 6s to run the tests now.  Also not sure if it will scale well to the material-motion-js monorepo, where the sources and builds are spread across different packages.

**Comment by appsforartists** [comment]
🎊 My diff is ready for review at http://codereview.cc/D2380
