### ISSUE TITLE
Investigate creating karma-tsickle preprocessor for unit testing

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#80]
Right now, we need to use webpack in our unit testing to resolve `import` statements.  This adds overhead we don't need - webpack is a bit slow, and the bundle it generates for testing isn't used for anything other than running the test.

tsickle replaces `import` statements with `goog.module`.  We ought to be able to write a karma preprocessor for tsickle, which would  fix the `import` mess without invoking all the bundling infrastructure.

**Comment by jverkoey** [comment]
I believe this is resolved.
