### ISSUE TITLE
Make unit testing work in arc lint

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#9]
Write tests, especially for the nitty-gritty in the Performers and Scheduler (e.g. the whole Runtime).
- Make sure `{x: 10, y: 10} + {x: 48} = {x: 58, y: 10}`

[Notes comparing test tools](https://material-motion.gitbooks.io/material-motion-team/content/essentials/testing/javascript.html)

**Comment by appsforartists** [comment]
Remember to keep @jverkoey in-the-loop so Phabricator can run these automatically.

**Comment by jverkoey** [comment]
We'll likely want our tests to run on travis in the long term, but we can def hook up local `arc unit` integrations in the near term (finding problems before sending code out for review is 👍  ).

**Comment by appsforartists** [comment]
Looks like Karma hooks up to Google infrastructure for auto-testing.  Is that a point in its favor?  Should we be running our test on internal infrastructure?

**Comment by appsforartists** [comment]
https://github.com/tagview/arcanist-extensions

**Comment by appsforartists** [comment]
I wonder if this is still worth doing, since we have CircleCI now.  Not sure I want my diffs blocked on local `arc unit`

**Comment by appsforartists** [comment]
We have CI now, so meh.
