### ISSUE TITLE
Find the right shape for a target

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#95]
There are a myriad of JavaScript view frameworks that manage state differently.  Even something as simple as setting a style is done with dictionaries in React-style frameworks and with setters on DOM nodes in others.

In order to enable motion to be reusable across frameworks, it may be beneficial to have a consistent `target`  shape that abstracts over these differences.  I experimented with [a shape for this](http://1-dot-codereview-cc-cluster.appspot.com/file/data/rk3r3gl33doiiqjvxhmd/PHID-FILE-455stsft3g6ha56t7myi/src_react_DirectorTarget.jsx) in the RxJS/React experiments.

At a minimum, the right shape probably includes the abilities to get/set styles, get/set arbitrary data, and get a pointer stream.
- Is it possible to have a single shape that works for all view frameworks and all potential performers?  What if a performer wanted to step a frame in a filmstrip component, or change some SVG geometry?  Presumably, both cases would pass pure data back to the view framework to adjust its parameters accordingly.  Getting a pointer event stream or setting styles might be nonsensical in these cases; should those elements need to bake that functionality into their targets just to have the right shape?
- If not, how do we validate that a target:performer pair are compatible?  Does each performer do its own assertion, or is this enforced by Material Motion?  (This is a similar problem to allowing performers to announce which kinds of plans they support, and having Material Motion choose the best fit.)

Related: #77 (TypedOM exploration)

**Comment by jverkoey** [comment]
I believe this is resolved with latest spec.
