### ISSUE TITLE
Explore input/output mapping mechanism for Performers with as minimal implementation weight as possible and reasonable public API given domain of interaction design

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-experiments-js#96]

**Comment by appsforartists** [comment]
_this is out-of-date.  was in my snippets, but doesn't belong there.  posting here for posterity:_
- Propose a variation of Material Motion where the output of one performer can feed into the input of another
- Need a high-level tooling visualization system (e.g. Stage or Remixer can see a plan+performer and know what the inputs/outputs are)
- Don't take anything for granted.  Anything in the current system could need modification
- Don't jump straight to RxJS.  Operators like zip may not be useful in animation.  An animation is probably driven by one of {pointer, time, scroll position}, not all in concert.
- Use cases:
  - Driving a timeline via gesture progress.
  - Driving a CSS value via scroll position.
  - Triggering a tween via timeline position
  - Is a composition a director + the concept of progress?
- You could, for instance, package "FAB expansion" in a composition.  Its internals would be opaque to the composition that mounts it, but internally, maybe it springs a FAB open/closed and also changes its shadow.

**Comment by appsforartists** [comment]
code sketches: http://codereview.cc/D1875
TODO: prototype how these might be visualized in a tool (https://github.com/material-motion/material-motion/issues/16)

**Comment by appsforartists** [comment]
Useful operators that can be described declaratively and visualized in a tool:
- min/max
- pluck
- interpolate
- shift: `map(value => value + offset)`
- scale: `map(value => value * coefficient)`
- debounce
- distinct
- threshold: measure if the incoming stream is >, >=, <, or <= a particular threshold; useful for mapping pointerStream.pointers.length to isAtRest
- to/from polar coords

Useful primitives:
- dragStream/rotateStream/scaleStream (should these be combined?)
- scrollStream
- timeStream
- streamSwitch: takes three streams.  mirrors stream1 while source emits true and stream2 if it emits false.  Useful for ignoring springs when pointerStream isn't at rest
- spring

Each operator should remember its configuration and its source.  To visualize a stream, walk each operator's source until you get to the root and read their configs.  Each parameter in a config should accept a value or a stream of values.  When a parameter stream emits a new value, the operator should recalculate itself and emit in kind.  The tooling would need to be able to tell any operator to reconfigure itself and emit a new value accordingly.

**Comment by appsforartists** [comment]
Moving explorations to https://github.com/material-motion/streams-experiment-js/tree/develop/packages/streams/#readme to avoid distractions in main repo.
